export const LOGIN = "LOGIN";
export const SIGN_UP = "SIGN_UP";

//PROJECT
export const CREATE_PROJECT = "CREATE_PROJECT";
export const QUERY_USER_PROJECT = "QUERY_USER_PROJECT";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";

//CAMPAIGN
export const CREATE_CAMPAIGN = "CREATE_CAMPAIGN";
export const QUERY_CAMPAIGN = "QUERY_CAMPAIGN";
export const SET_CURRENT_CAMPAIGN = "SET_CURRENT_CAMPAIGN";
